### ISSUE TITLE
will not load FFXIV profile with link

### ISSUE THREAD

**Issue by pokenerd34** [bdejesus/twitch-xiv-profile#20] opened 2024-01-30 02:50 UTC
**Describe the bug**

**To Reproduce**
1. Go to '...' [Visit the Final Fantasy Lodestone website](https://na.finalfantasyxiv.com/lodestone/) and log in with your account to access your character profile.
2. Click on '....' logged in
3. Scroll down to '....' profile
4. See error Could not find character. Please make sure you entered the correct ID or URL.

**Expected behavior**
A clear and concise description of what you expected to happen. Load FFXIV lodestone profile

**Screenshots**
![image](https://github.com/bdejesus/twitch-xiv-profile/assets/104335692/72c61602-cf10-4769-9c04-67a096733f9b)

**Browser Info (please complete the following information):**
 - OS: [e.g. Windows/Mac]  Windows 
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  Chrome is up to date
Version 121.0.6167.86 (Official Build) (64-bit)

**Additional context**

**Comment by neotantrix** [comment] 2024-02-06 09:34
fucking seconded. i tried my char id, lodestone link, tried getting both while incognito, while signed in, it just does not link

**Comment by bdejesus** [comment] 2024-02-06 16:29
Hey all, thanks for reporting. There's a fix on the way, but Twitch is taking a long time to review extension updates since they've updated their internal processes.

(closing because this is a duplicate of https://github.com/bdejesus/twitch-xiv-profile/issues/13)

**Closed by bdejesus** 2024-02-06 16:29 UTC
Labels: duplicate
